### ISSUE TITLE
Se et overblik over et projekt

### ISSUE THREAD

**Issue by jazzyzoney** [jazzyzoney/BetaSolutions#11]
Som bruger vil jeg gerne kunne se et overblik over et igangværende projekt på en side, så jeg har styr på det

_siden skal bare være et tomt projekt_

**task**

- [x] Der skal skrives en Read metode som læser et project fra databasen og viser det på siden. 
- [x] Der skal være en service som passere metoden til controlleren 
- [x] der skal være en controller som returner en side hvor projektet kan vises
- [x] der skal være en html som kan vise et proejct på siden 

**acceptkriterier**
- Når et projekt bliver vist på en side. 
- når projektet har de oplysninger som det har i databasen 
- når der er blevet lavet test a read metoden
