### ISSUE TITLE
Summering af tidsforbrug

### ISSUE THREAD

**Issue by jazzyzoney** [jazzyzoney/BetaSolutions#14]
Som bruger vil jeg gerne kunne se en summering af tidsforbrug, så jeg har en ide om hvor lang tid et projekt vil tage

**task**

- [x] omregne timer til dage
- [x] opdateret ER-model og h2 til at  indeholde specifikke timer go totale timer
- [x] når en subtask oprettes, opdateres task totale timer + dage.
- [ ] når en tasks totale timer opdateres, opdateres subprojects totale time + dage.
- [ ] når et subprojects totale timer opdateres, opdateres projektets totale timer.
- [ ] display summen af timer og summen af dage

**acceptkriterier**
- når man kan taste tidsforbruget ind og se en summering af det samlede forbrug
- hvis opgaverne bliver opdateret, opdateres summen af tidsforbruget automatisk.
- summeringen foregår i service-laget
- gennemtestet
