### ISSUE TITLE
Fordeling af tidsforbrug

### ISSUE THREAD

**Issue by jazzyzoney** [jazzyzoney/BetaSolutions#15]
Som projektleder kan jeg hvor mange timer, der skal arbejdes hver dag i gennemsnit, så jeg kan planlægge efter vores deadline.

_kan ikke laves før summering af tidsforbrug er færdig_

**task**

- [ ] udregne gennemsnits timer om dagen, baseret på deadline og indtastede timer.
- [ ] udregne hvor mange timer, der er tilbage i projektet.
- [ ] udregne, hvor mange arbejdsdage der er til deadline. Der tages højde for weekender, men ikke for ferier.

**acceptkriterier**

- når man kan se hvor mange timer det forventes at arbejde hver dag
- når man kan se hvor mange timer der skal til for at man bliver færdig med projektet
