### ISSUE TITLE
Se en samlet udgift over et projekt

### ISSUE THREAD

**Issue by jazzyzoney** [jazzyzoney/BetaSolutions#16]
Som bruger vil jeg gerne kunne se et samlet budget over et projekt, så jeg ved hvor meget projektet kommer til at koste 

**task**
- [ ] budgetside
- [ ] man skal kunne tilføje til budgetet 
- [ ] Det skal selv udregne totalen af bdugetet 
- [ ] man skal også kunne slette udgifter fra budget efter det er blevet tilføjet 
- [ ] man skal kunne ændre en udgift. 
- [ ] indtaste indtægter.

**acceptkriterier**
- Når man kan se et budget til et bestemt project
- Når jeg kan opdatere et budget og den totale udgift bliver ændret løbende. 
- når jeg kan slette elementer af budgetet. 
- når der er lavet test på crud metoderne.
