### ISSUE TITLE
Oprette tasks

### ISSUE THREAD

**Issue by jazzyzoney** [jazzyzoney/BetaSolutions#25]
Som bruger vil jeg gerne kunne oprette tasks til et projekt, så jeg nemmere kan uddele opgaver

**task**

- [x] Man skal kunne oprette en task. 
- [x] man skal kunne fjerne en task 
- [x] man skal kunne se alle tasks som lægger på et projekt. 

**acceptkriterier**
- Jeg skal kunnne oprette tasks til et projekt
- tasks som lægger til et projekt bliver gemt i databasen. 
- Der skal laves test a CRUD metoderne
