### ISSUE TITLE
Oprette sub tasks

### ISSUE THREAD

**Issue by jazzyzoney** [jazzyzoney/BetaSolutions#26]
Som bruger vil jeg gerne kunne oprette sub tasks, så jeg kan inddele en task i flere dele

**task**
- [x]  Man skal kunne opratte en sub task.
- [x] man skal kunne se  sub task oprattet under et projekt.
- [x] man skal kunne fjerne en sub task
- [x] man skal kunne se alle  sub task som lægger på et projekt.

acceptkriterier
- Jeg skal kunnne oprette tasks til et projekt og de tasks som lægger til et projekt bliver gemt i databasen.
- Der skal laves test a crud metoderne

**Comment by signelystrup** [comment]
subtasks ligger allerede på master. 
Vi ville merge branchen igen alligevel, men det kører ikke, så vi lader bare være, for det virker allerede.
