### ISSUE TITLE
Oprette sub projects

### ISSUE THREAD

**Issue by jazzyzoney** [jazzyzoney/BetaSolutions#27]
Som bruger vil jeg gerne kunne oprette sub projects, så jeg kan inddele et projekt i flere dele 

**task**
- [x]  Man skal kunne opratte en sub projects.
- [x] man skal kunne se  sub projects oprattet under et projekt.
- [x] man skal kunne fjerne en sub projects
- [x] man skal kunne se alle   sub projectet som lægger på et projekt.

**acceptkriterier**
- Jeg skal kunnne opratte tasks til et projekt og de tasks som lægger til et projekt bliver gemt i databasen.
- Der skal laves test a crud metoderne
